# Generated by Django 5.2.3 on 2025-06-11 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[('id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )),
                    ('name', models.CharField(max_length=100)),
                    ('description', models.TextField()),
                    ('country_name', models.CharField(
                                        blank=True,
                                        max_length=50
                                    )),
                    ('country_iso2', models.CharField(
                                        blank=True,
                                        max_length=2
                                    )),
                    ('country_iso3', models.CharField(
                                        blank=True,
                                        max_length=3
                                    )),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=50)),
                ('car_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('WAGON', 'Wagon'),
                    ('SUV', 'SUV'), ('COUPE', 'Coupe'), ('PICKUP', 'Pickup'), ('VAN', 'Van')], max_length=20)),
                ('car_fuel_type', models.CharField(blank=True, choices=[('GASOLINE', 'Gasoline'),
                    ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('BIO-DIESEL', 'Bio-Diesel'), ('LPG', 'LPG'),
                    ('ETHANOL', 'Ethanol'), ('METHANOL', 'Methanol'), ('HYDROGEN', 'Hydrogen'),
                    ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid (Plug-in & Non-Plug-in)'),
                    ('SOLAR', 'Solar Powered')], max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2025), 
                                                        django.core.validators.MinValueValidator(2000)
                                                        ])),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='djangoapp.carmake'
                                                )),
            ],
        ),
    ]
